# Command launcher file for `just`.

[private]
default:
    just --list

# Runs the part 1 puzzle with the test input.
test1a:
    python3 part1.py --input test_a.txt

test1b:
    python3 part1.py --input test_b.txt

# Runs the part 2 puzzle with the test input.
test2a:
    python3 part2.py --input test_a.txt

test2b:
    python3 part2.py --input test_b.txt

# Runs the part 1 puzzle with the challenge input.
part1:
    python3 part1.py --input input.txt

# Runs the part 2 puzzle with the challenge input.
part2:
    python3 part2.py --input input.txt
